import { Plus_Jakarta_Sans } from "next/font/google";
import "../globals.css";
import BackgroundOverlay from "./background-overlay";

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function FormLayout({ children }) {
  return (
    <html lang="en">
      <body className={plusJakartaSans.className}>
        <BackgroundOverlay>
          {children}
        </BackgroundOverlay>
      </body>
    </html>
  );
}
